{% set name = "fisspy" %}
{% set version = "1.0.4" %}

package:
  name: fisspy
  version: {{ version }}

source:
  fn: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bf941aa914010123898f8556f48b60ece9554f90a7a3beede1bdfb9f732685e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - numba
    - pyqt
    - scipy
    - astropy
    - sunpy
    - matplotlib
    - interpolation
    - statsmodels
    - beautifulsoup4
    - pandas
    - ffmpeg

test:
  imports:
    - fisspy
  requires:
    - pip
  command:
    - pip check

about:
  home: https://github.com/SNU-sunday/fisspy
  license: BSD-2
  summary: The Python Package for data analysis of the GST/FISS Instrument
  description: |
    None
  doc_url: http://fiss.snu.ac.kr/fisspy/